# fly.toml app configuration file generated for pebble-server on 2023-11-10T16:22:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pebble-server"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
